
  (autoload 'color-theme-install "color-theme" "color-theme" t)


(defun color-theme-dark-green ()
  "Color theme by ces93, created 2002-03-30."
  (interactive)
  (color-theme-install
   '(color-theme-dark-green
     ((background-mode . light)
      (background-toolbar-color . "#e79ddf7ddf7d")
      (border-color . "#000000000000")
      (bottom-toolbar-shadow-color . "#8e3886178617")
      (top-toolbar-shadow-color . "#ffffffffffff"))
     nil
     (default ((t (nil))))
     (blue ((t (:foreground "blue"))))
     (bold ((t (:bold t))))
     (bold-italic ((t (:italic t :bold t))))
     (border-glyph ((t (nil))))
     (fringe ((t (nil))))
     (green ((t (:foreground "green"))))
     (gui-button-face ((t (:background "grey75" :foreground "black"))))
     (gui-element ((t (:background "#ffffff" :foreground "#000000"))))
     (highlight ((t (:background "gray" :foreground "darkred"))))
     (isearch ((t (:background "LightSlateGray" :foreground "red"))))
     (italic ((t (:italic t))))
     (left-margin ((t (nil))))
     (list-mode-item-selected ((t (:background "gray68"))))
     (mode-line ((t (:background "LightSlateGray" :foreground "black"))))
     (modeline ((t (:background "LightSlateGray" :foreground "black"))))
     (modeline-buffer-id ((t (:background "LightSlateGray" :foreground "blue4"))))
     (modeline-mousable ((t (:background "LightSlateGray" :foreground "firebrick"))))
     (modeline-mousable-minor-mode ((t (:background "LightSlateGray" :foreground "green4"))))
     (pointer ((t (:background "#ffffff" :foreground "#000000"))))
     (primary-selection ((t (:background "gray65"))))
     (red ((t (:foreground "red"))))
     (region ((t (:background "gray65"))))
     (right-margin ((t (nil))))
     (rpm-spec-dir-face ((t (:foreground "green"))))
     (rpm-spec-doc-face ((t (:foreground "magenta"))))
     (rpm-spec-ghost-face ((t (:foreground "red"))))
     (rpm-spec-macro-face ((t (:foreground "purple"))))
     (rpm-spec-package-face ((t (:foreground "red"))))
     (rpm-spec-tag-face ((t (:foreground "blue"))))
     (secondary-selection ((t (:background "paleturquoise"))))
     (text-cursor ((t (:background "Red3" :foreground "DarkSlateGray"))))
     (tool-bar ((t (nil))))
     (toolbar ((t (:background "#ffffff" :foreground "#000000"))))
     (underline ((t (:underline t))))
     (vertical-divider ((t (:background "#ffffff" :foreground "#000000"))))
     (widget-button-face ((t (:bold t))))
     (widget-button-pressed-face ((t (:foreground "red"))))
     (widget-documentation-face ((t (:foreground "dark green"))))
     (widget-field-face ((t (:background "gray85"))))
     (widget-inactive-face ((t (:foreground "dim gray"))))
     (yellow ((t (:foreground "yellow"))))
     (zmacs-region ((t (:background "darkorange" :foreground "black")))))))
