
  (autoload 'color-theme-install "color-theme" "color-theme" t)


(defun color-theme-renegade ()
 "Renegade BBS styled color theme. Works well in X and terminals.
Created by Dave Benjamin <ramen@ramenfest.com> Dec 23 2005."
 (interactive)
 (color-theme-install
  '(color-theme-renegade
    ((background-color . "black")
     (background-mode . dark)
     (border-color . "black")
     (cursor-color . "black")
     (foreground-color . "cyan3")
     (mouse-color . "white"))
    (default ((t (nil))))
    (bold ((t (:bold t :foreground "cyan" :weight bold))))
    (bold-italic ((t (:italic t :bold t :foreground "cyan" :slant italic :weight bold))))
    (fixed-pitch ((t (:family "courier"))))
    (font-lock-builtin-face ((t (:bold t :foreground "cornflower blue" :weight bold))))
    (font-lock-comment-face ((t (:bold t :foreground "yellow" :weight bold))))
    (font-lock-constant-face ((t (:foreground "magenta3"))))
    (font-lock-doc-face ((t (:bold t :weight bold :foreground "red"))))
    (font-lock-function-name-face ((t (:foreground "gray"))))
    (font-lock-keyword-face ((t (:bold t :foreground "cyan" :weight bold))))
    (font-lock-string-face ((t (:bold t :foreground "red" :weight bold))))
    (font-lock-type-face ((t (:bold t :foreground "cyan" :weight bold))))
    (font-lock-variable-name-face ((t (:foreground "cyan3"))))
    (font-lock-warning-face ((t (:bold t :foreground "red" :weight bold))))
    (fringe ((t (:background "gray32"))))
    (highlight ((t (:background "blue"))))
    (isearch ((t (:background "blue" :foreground "cyan3"))))
    (isearch-lazy-highlight-face ((t (:background "turquoise3" :foreground "black"))))
    (menu ((t (nil))))
    (mode-line ((t (:bold t :background "blue3" :foreground "white" :box (:line-width -1 :style released-button) :weight bold))))
    (mouse ((t (:background "white"))))
    (region ((t (:bold t :background "white" :foreground "blue" :weight bold))))
    (scroll-bar ((t (nil))))
    (trailing-whitespace ((t (:background "red"))))
    (underline ((t (:underline t))))
    (variable-pitch ((t (:family "helv")))))))
